#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Application\Command\Cache;
use Application\Foundation\Config;
use Application\Service\Mail;
use Colibri\Console\Application;
use Colibri\Database\Db;

Db::setConfig(Config::database());
Mail::setConfig(Config::mail());


/** @noinspection PhpUnhandledExceptionInspection */
$code = (new Application('Colibri Fly Tools', 'dev'))
    ->setLogo('<fg=cyan>  _                      ___        ____
 / )     /  \'  /  _  \'  (_    /      /          /   _
(__  () (  /  () /  /   /    (  (/  (    () () (  _)
                                /                     </>')
    ->addCommands([
        new Cache\Clear(),
    ])
    ->run()
;

exit($code);
